// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using primeraApi.Modelos.Datos;

#nullable disable

namespace primeraApi.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20231023234354_agregardatos")]
    partial class agregardatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("primeraApi.Modelos.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizacionFecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MetrosCuadrados")
                        .HasColumnType("float");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupantes")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActualizacionFecha = new DateTime(2023, 10, 23, 17, 43, 54, 201, DateTimeKind.Local).AddTicks(6167),
                            Amenidad = "",
                            Detalle = "detalle de la villa",
                            FechaCreacion = new DateTime(2023, 10, 23, 17, 43, 54, 201, DateTimeKind.Local).AddTicks(6150),
                            ImagenUrl = "",
                            MetrosCuadrados = 25.0,
                            Nombre = "Villa San alejandro",
                            Ocupantes = 54,
                            Tarifa = 200.0
                        },
                        new
                        {
                            Id = 2,
                            ActualizacionFecha = new DateTime(2023, 10, 23, 17, 43, 54, 201, DateTimeKind.Local).AddTicks(6178),
                            Amenidad = "",
                            Detalle = "Mira esto",
                            FechaCreacion = new DateTime(2023, 10, 23, 17, 43, 54, 201, DateTimeKind.Local).AddTicks(6178),
                            ImagenUrl = "",
                            MetrosCuadrados = 2534.0,
                            Nombre = "No se que onda",
                            Ocupantes = 544,
                            Tarifa = 200543.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
